name: test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20", "latest"]
        chai: ["4", "5", "6"]
    name: Node ${{ matrix.node }} / chai ${{ matrix.chai }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
      - name: Install chai ${{ matrix.chai }}
        run: yarn add --dev chai@${{ matrix.chai }}
      - run: yarn test
      - run: yarn code:check
      - run: yarn type:check
